import type { ProjectsResponse } from '../../types/project'

// Données de démonstration. À remplacer par un appel à votre API Deplay.
export const projectsResponse: ProjectsResponse = {
  projects: [
    {
      id: 'fabrich-profile',
      name: 'fabrich-profile',
      url: 'fabrich-profil.vercel.app',
      description: 'Application de gestion de profil et d’identité utilisateur.',
      kind: 'none',
      status: 'live',
      branch: 'main',
      updatedAt: '2026-10-03T09:00:00Z',
      updatedLabel: '2h ago',
      stats: { deployments: 24, requests: '12.4k', errors: '0.02%' },
      sparkline: [4, 5, 4, 6, 5, 7, 6, 8, 7, 9, 8, 9],
    },
    {
      id: 'model-scraper',
      name: 'model-scraper',
      url: 'free-pornhub-downloader.vercel.app',
      description: 'Outils de scraping et téléchargement de contenu multimédia.',
      kind: 'none',
      status: 'building',
      branch: 'main',
      updatedAt: '2026-10-02T21:00:00Z',
      updatedLabel: '1d ago',
      stats: { deployments: 16, requests: '4.8k', errors: '0.12%' },
      sparkline: [3, 4, 3, 5, 4, 6, 5, 6, 5, 7, 6, 7],
    },
    {
      id: 'epta',
      name: 'epta',
      url: 'epta-eight.vercel.app',
      description: 'Plateforme de visualisation et d’analyse de données.',
      kind: 'react',
      status: 'live',
      branch: 'main',
      updatedAt: '2026-04-18T10:00:00Z',
      updatedLabel: 'Apr 18',
      stats: { deployments: 18, requests: '8.6k', errors: '0.05%' },
      sparkline: [5, 6, 5, 7, 6, 8, 6, 7, 8, 7, 9, 8],
    },
    {
      id: 'land',
      name: 'land',
      url: 'land-tgn-swart.vercel.app',
      description: 'Site Web de présentation et portfolio professionnel.',
      kind: 'none',
      status: 'attention',
      branch: 'main',
      updatedAt: '2026-01-27T10:00:00Z',
      updatedLabel: 'Jan 27',
      stats: { deployments: 11, requests: '3.2k', errors: '0.48%' },
      sparkline: [6, 5, 7, 6, 5, 6, 7, 6, 8, 7, 8, 7],
    },
    {
      id: 'sagebiz-stunning',
      name: 'sagebiz-stunning',
      url: 'sagebiz-stunning.vercel.app',
      description: 'Plateforme e-commerce moderne et rapide.',
      kind: 'bolt',
      status: 'live',
      branch: 'main',
      updatedAt: '2025-11-24T10:00:00Z',
      updatedLabel: '11/24/25',
      stats: { deployments: 27, requests: '15.3k', errors: '0.03%' },
      sparkline: [7, 8, 7, 9, 8, 9, 10, 9, 10, 9, 11, 10],
    },
    {
      id: 'rank-member-linear',
      name: 'rank-member-linear',
      url: 'rank-member-linear.vercel.app',
      description: 'Outil de gestion des membres et de classement.',
      kind: 'bolt',
      status: 'live',
      branch: 'main',
      updatedAt: '2025-10-28T10:00:00Z',
      updatedLabel: '10/28/25',
      stats: { deployments: 8, requests: '2.7k', errors: '0.06%' },
      sparkline: [2, 3, 3, 4, 3, 4, 4, 5, 4, 5, 5, 6],
    },
  ],
  usage: {
    usedPercent: 72,
    period: 'Last 30 days',
    items: [
      { label: 'Deployment Storage', value: '2.87 MB / 10 GB', percent: 29, icon: 'box' },
      { label: 'CDN Requests', value: '90 / 1M', percent: 2, icon: 'globe' },
      { label: 'Fast Data Transfer', value: '2.07 MB / 100 GB', percent: 2, icon: 'activity' },
      { label: 'Fast Origin Transfer', value: '0 / 10 GB', percent: 0, icon: 'server' },
    ],
  },
}
