import type { Deployment } from '../../types/deployment'

// Données de démonstration. À remplacer par un appel à votre API Deplay.
export const deployments: Record<string, Deployment> = {
  'todo-maaster': {
    id: 'todo-maaster',
    name: 'todo-maaster',
    description: 'Task management app with real-time features, built with Next.js and Express.',
    type: 'Web Application',
    runtime: 'Node.js',
    environment: 'Production',
    url: 'todo-mail.duckdns.org',
    branch: 'main',
    commit: 'a1b2c3d4',
    status: 'deployed',
    deployedAt: 'Oct 2, 2026 • 21:34',
    duration: '6m 52s',
    steps: [
      { key: 'build', label: 'Build', duration: '2m 14s', status: 'done' },
      { key: 'test', label: 'Test', duration: '1m 32s', status: 'done' },
      { key: 'deploy', label: 'Deploy', duration: '1m 08s', status: 'done' },
      { key: 'live', label: 'Live', duration: 'Done', status: 'done' },
    ],
    logs: [
      { time: '21:32:11', message: 'Cloning repository...', tone: 'default' },
      { time: '21:32:14', message: 'Fetching submodules...', tone: 'default' },
      { time: '21:32:16', message: 'Installing dependencies...', tone: 'default' },
      { time: '21:32:38', message: 'Building application...', tone: 'default' },
      { time: '21:33:05', message: 'Running tests...', tone: 'default' },
      { time: '21:33:21', message: 'Preparing deployment...', tone: 'default' },
      { time: '21:33:42', message: 'Uploading to server (2.4 MB)...', tone: 'muted' },
      { time: '21:33:58', message: 'Restarting PM2 process...', tone: 'default' },
      { time: '21:34:03', message: 'Application is now running at port 3000', tone: 'success' },
      { time: '21:34:03', message: 'Deployment completed successfully! 🎉', tone: 'success' },
    ],
    info: {
      name: 'todo-maaster',
      framework: 'Next.js 14',
      runtime: 'Node.js 18',
      port: 3000,
      memory: '512 MB',
      cpu: '0.5 vCPU',
      created: 'Aug 12, 2026',
    },
    server: {
      status: 'online',
      ip: '154.51.63.78',
      provider: 'VPS (2 GB)',
      location: 'Madagascar',
      flag: '🇲🇬',
    },
    metrics: [
      {
        key: 'uptime',
        label: 'Uptime',
        value: '99.98%',
        delta: '+0.12%',
        icon: 'power',
        points: [99.2, 99.5, 99.3, 99.8, 99.7, 99.9, 99.98, 99.96, 99.99, 99.98],
      },
      {
        key: 'response',
        label: 'Response Time',
        value: '142 ms',
        delta: '-18%',
        icon: 'clock',
        points: [180, 160, 170, 150, 155, 148, 142, 145, 140, 142],
      },
      {
        key: 'traffic',
        label: 'Traffic',
        value: '2.4k req/min',
        delta: '+32%',
        icon: 'chart',
        points: [1.2, 1.5, 1.4, 1.8, 2.0, 2.1, 2.2, 2.3, 2.4, 2.4],
      },
    ],
  },
}
